version: 1.6.{build}
image:
  - Ubuntu
  - Visual Studio 2019
skip_tags: true
configuration: Release
before_build:
  - ps: >-
      nuget restore

build:
  project: iTextSharp.LGPLv2.Core.sln
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\iTextSharp.LGPLv2.Core.*.nupkg'
deploy:
  - provider: GitHub
    auth_token:
      secure: 1u8+Vw3eV9Wv45b7FC5FYAlO7xn6X6ov27BPDHx7hh3B4+E3UsE017aYq1WZbQvN
    prerelease: true
  - provider: NuGet
    api_key:
      secure: BAGacXk+5m7jd8EvWW6wkYhoVml39WAi7n2Z0odVUKUq5SeWLqixvkPA1I+KbQ1r
    on:
      branch: master
