version: 1.1.{build}
image: Visual Studio 2019
skip_tags: true
branches:
  only:
    - master
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
  - ps: >-
      nuget restore

      . "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\x64\sn.exe" -k ./src/iTextSharp.LGPLv2.Core/iTextSharp.LGPLv2.Core.snk
build:
  project: iTextSharp.LGPLv2.Core.sln
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\iTextSharp.LGPLv2.Core.*.nupkg'
deploy:
  - provider: GitHub
    auth_token:
      secure: 1u8+Vw3eV9Wv45b7FC5FYAlO7xn6X6ov27BPDHx7hh3B4+E3UsE017aYq1WZbQvN
  - provider: NuGet
    api_key:
      secure: BAGacXk+5m7jd8EvWW6wkYhoVml39WAi7n2Z0odVUKUq5SeWLqixvkPA1I+KbQ1r
